version: '3.8'

services:
  telegram_x_video_bot:
    image: harveyl/telegram_x_video_bot:latest
    container_name: telegram_x_video_bot
    restart: unless-stopped
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - RUST_LOG=info
    volumes:
      - ./twitter.txt:/app/twitter.txt
      - ./video:/app/video
    network:
      - botnet

networks:
  botnet:
    driver: bridge
